### ISSUE TITLE
UI wireframes/mockups

### ISSUE THREAD

**Issue by OFFLlNE** [OFFLlNE/PSP#25]
Application UI is prototyped using wireframes or mockyps and the detailed requirements contain are linked to the corresponding UI screens.

**Comment by erxor** [comment]
https://github.com/OFFLlNE/PSP/commit/a16faa8ccbab15a2feb559b9e3f318b183fab981

**Comment by erxor** [comment]
https://github.com/OFFLlNE/PSP/commit/dcd9abcb5072a700298eb2785290f2be8dd6c5e8
