### ISSUE TITLE
2nd iteration feedback

### ISSUE THREAD

**Issue by huberflores** [OFFLlNE/PSP#27]
Prior giving feedback for 2nd iteration, please start making a quick check about the deliverables https://courses.cs.ut.ee/2015/tvp/fall/Main/Second-iteration

**Comment by huberflores** [comment]
Please find below the feedback from your work done in the 2nd iteration.

Application.
- The application covers at least the required functionality for this iteration.
- I am wondering if the customer has already try the application or not? and the satisfaction of the customer with the current development, plan, goals, etc?  This information should be located in the "meetings with customer" page

Building process.
- The building process is not explained. Naturally, since the project is with maven, it is easy to build the application running "mvn install". However, it is not always the case that an application can be built just with that command. There are parameters that need to be fullfil in order to build the project, for instance, maven version to use, local maven dependencies (if any), etc. This issue can be fix easily by putting in the wiki instructions about how to build it and the requirements to build it, e.g., mvn higher than 3.3. Ideally, there should be a unique script that calls "mvn install" & applies the tests of Sikuli as well.

Continuous integration.
- This is a desktop application, so continous integration will be manage by parts. Maven for building the application and sikuli for tests. Maven is in place, but I didn't see any Sikuli. Please elaborate as CI for desktop applications will be graded based on Sikuli utilization.

Detailed requirements.
- The detailed requirements are consistent with the initial requirements, meaning that the development is going as expected. The detailed requirements also considered different flows, e.g., errors. Perhaps the only addition to the current format of requirements is what happens after an exception arises, e.g., a help window popup up showing how it has to be done, and one the user clicks ok, return to the application.

UI wireframes/mockups:
- The mockups of your application are not very understandable, in order to fix this, I propose to introduce within the mockups some arrows with comments and steps (numbers), for instance, 1) user selects new project, 2) draws parking places, 3) draws cars, 4) press button to calculate and so on.

Scope:
- It is unclear how you divide the tasks and how are you planning to continue working the next iteration. Thus, I propose to create a spreadsheet with more detail information about the task, time assigned, person assigned, status (complete or on-going), etc. You may also use any other tool of your preference, e.g., Trello

Release notes:
- Release notes are ok.  

Collaboration infrastructure:
- Issues are created and assigned to the respective milestone as expected. Please also include the subissues within the milestone (if any) I can see some other issues in progress, so I am wondering if there are subissues from main issues. Finally, commits do no have associated issue (as shown initially in the first session), every commit must have an issue associated, e.g., "Polished the image a bit #10". Currently, I cannot track commits to issues. I am not sure if the application is too easy, or the team does not commit periodically. Do no wait until the end of the deadline to commit the development. 

Summary:
Currently, I cannot see an even distribution of load in the project. Thus, I encourage you to create the spreadsheet mentioned in scope. I know that there is also effort going on the wiki and making the mockups, etc, so, in order to quantify the effort of each member, it is necessary to be able to see the overall management of the project. 

The questions asked in this feedback can be answered in this thread. Please also apply the changes of the feedback. If some changes need discussion, then those questions also can be raised here.

**Comment by OFFLlNE** [comment]
Our client has got the code and he has been able to run the program by himself.
Added feedback of our project from our last meeting to the meetings page

**Comment by OFFLlNE** [comment]
Added workload spreadsheet. Main things are written down, might be some additions overtime
https://docs.google.com/spreadsheets/d/1OuCGpvD8auPTHbgH3EnaocIXjdUv3V2v9CKfRTSeSHQ/edit?usp=sharing
