### ISSUE TITLE
1st iteration feedback

### ISSUE THREAD

**Issue by huberflores** [OFFLlNE/PSP#5]
Please find below the feedback from your work done in the 1st iteration.

Wiki
Homepage (Vision)
- Limitations can be set in order to define specifically the purpose of the application, e.g., it can be used just by developers, it can be used by any person, etc.
- Some text polishing could help to understand more clearly the vision of the application, for instance, it is not very clear what you meant by "The program will give the user Robot parking lot in the same space, but with more parking spots." You could start by defining the terminology used by your application, e.g., what is the purpose of the robot/platform in this context? 

Functional requirements.
- Define the actors of the system. This can be easily fixed by providing an overview about how do you envision that the application will work. This can be written before staring your FR. In this manner, you can properly refer to a specific actor within your requirements. For instance, a user uploads a parking lot schema to the application. Currently, some requirements just generalizes functionality, which is not very clear to who is provided. Try to follow a format "X" does/should do/generates "Y". 
- Some requirements are not very clear, more specific details are missing. For instance, what the properties required by the app to read a parking lot schema? what is the type of the image you are reading? when drawing the parking lot, how can differentiate a door from a window? and so on. Reading the critic section of this link may help to understand the issue (http://users.csc.calpoly.edu/~jdalbey/SWE/QA/nonfunctionalExamples.html)
- Entities of your application should be defined, e.g., what is a standard car defined? what is a standard parking spot? how many cars can fit into a standard parking spot? By reading the requirements I could assume multiple things, but this should be written concretly in order to avoid ambiguity. 

Non-Functional requirements
- Try to locate non-functional requirements into a well defined category, for instance, 1. Performance, 1.1. The response time of the algorithm should be under 10 seconds for calculating the optimal distribution of cars in the parking lot, 1.2. The response time of the application should be under 2 seconds when interacting with the user. 2. Fault tolerance, 2.1....., 2.2.... 3. Reliability, 3.1...., 3.2.....
- It will be a good idea also to mention what is the alternative functionality if the application fails for all the requirements, for instance, the algorithm time is beyond 10 seconds, then what happens?
- Actually, there is a mismatch between the requirements 2 and 6. How are you planning to provide 2 seconds responsiveness if it takes 10 seconds to the algorithm to convert parking lot to a robot parking lot (whatever that means)
- This requirements also lack from clarity. For instance, (Robot amount has to be changable 1-2 clicks) and (Robot speed has to be changable in 1-3 clicks). It means that if the user provides 1 click, then the amount of Robots changed or Robot just speeds up? or do you mean that exact to click over the robot are required to change the amount of the Robot? same for the Robot speed.
- Finally, requirements can be associated to a priority in order to define effort and workload. Same with FR.

Project Plan
- Current plan is not consistent with the requirements, there should be an obvious mapping between the plan and how the requirements will be completed.
- Testing should be in every iteration when developing the application

Team structure.
- The roles are brief and clear. However it is unclear what back-end or front-end you will have. This means that requirements must be improved.

Team communication with the customer
- During the project, it would be good to schedule regular meetings, which are fixed. 

Work process
- This section is fine, but it may benefit from some polishing and restructuring. For instance, you can start by saying what kind of methodology you will follow, e.g., SPRING methodology. Then, you can mention the technologies that you will use to manager your project, e.g., Trello and Toggl. Finally, you can describe the iterative process you will follow, this includes, integrating feedback from customer, releasing a version of the the application, verification of the feedback integrated in the latest release and so on. Naturally, as stated in this section, it is expected that in the future more details will be in place.

Wiki
- Meetings with the customer and mentor also should be linked from the homepage by a "meetings" page.
- Remember that during the project, once one requirement is done, then this has to be mapped to the requirement located in the wiki.

Issue tracker
- The milestone "Wiki has to be done" is in fact "1st iteration"
- As we discussed in the meeting, you can create a few issues, for instance, creating "functional requirements" and you can close the issue with a link to that page. 

VCS.
- Issues and sub-issues should be linked (when applicable). Each commit should be associated their respective issue. Finally, remember to close each issue with the last token commit as seen in the meeting.

Transparency. 
- Not graded in this iteration, but it has to be considered from now. This point means that all the requirements, wiki, issue tracker, etc. are well integrated. In short, there should be consistency in the project, e.g., the requirements of the wiki must match the issues of the issue tracker.

Iterative tuning
- This issue can be used for tuning 1st iteration deliverable. Thus, after you applied changes, it may be possible to extend the discussion.

**Comment by OFFLlNE** [comment]
Added more detailed explanation of the program on the Homepage of Wiki

**Comment by OFFLlNE** [comment]
Polished, changed and edited Functional requirements

**Comment by OFFLlNE** [comment]
Added details to Project plan. (Testing before every iteration and added which functional requirements are done for certain month)

**Comment by OFFLlNE** [comment]
Added what front and back end are working on

**Comment by OFFLlNE** [comment]
Team communication with the customer - Added some minor details about meeting with the Client.
Since he does not live in Tartu and we dont need to have too many meetings, because we have pretty clear vision what the Client wants.

**Comment by OFFLlNE** [comment]
Everything is fixed now. Non-fun reqs, just need a little bit of additions and polishing
